const countries = [
  { label: "Afghanistan", value: "AFN", code: "AF", timezone: "Asia/Kabul" },
  { label: "Albania", value: "ALL", code: "AL", timezone: "Europe/Tirane" },
  { label: "Algeria", value: "DZD", code: "DZ", timezone: "Africa/Algiers" },
  { label: "Andorra", value: "EUR", code: "AD", timezone: "Europe/Andorra" },
  { label: "Angola", value: "AOA", code: "AO", timezone: "Africa/Luanda" },
  {
    label: "Antigua and Barbuda",
    value: "XCD",
    code: "AG",
    timezone: "America/Antigua",
  },
  {
    label: "Argentina",
    value: "ARS",
    code: "AR",
    timezone: "America/Argentina/Buenos_Aires",
  },
  { label: "Armenia", value: "AMD", code: "AM", timezone: "Asia/Yerevan" },
  {
    label: "Australia",
    value: "AUD",
    code: "AU",
    timezone: "Australia/Sydney",
  },
  { label: "Austria", value: "EUR", code: "AT", timezone: "Europe/Vienna" },
  { label: "Azerbaijan", value: "AZN", code: "AZ", timezone: "Asia/Baku" },
  { label: "Bahamas", value: "BSD", code: "BS", timezone: "America/Nassau" },
  { label: "Bahrain", value: "BHD", code: "BH", timezone: "Asia/Bahrain" },
  { label: "Bangladesh", value: "BDT", code: "BD", timezone: "Asia/Dhaka" },
  { label: "Barbados", value: "BBD", code: "BB", timezone: "America/Barbados" },
  { label: "Belarus", value: "BYN", code: "BY", timezone: "Europe/Minsk" },
  { label: "Belgium", value: "EUR", code: "BE", timezone: "Europe/Brussels" },
  { label: "Belize", value: "BZD", code: "BZ", timezone: "America/Belize" },
  { label: "Benin", value: "XOF", code: "BJ", timezone: "Africa/Porto-Novo" },
  { label: "Bhutan", value: "BTN", code: "BT", timezone: "Asia/Thimphu" },
  { label: "Bolivia", value: "BOB", code: "BO", timezone: "America/La_Paz" },
  {
    label: "Bosnia and Herzegovina",
    value: "BAM",
    code: "BA",
    timezone: "Europe/Sarajevo",
  },
  { label: "Botswana", value: "BWP", code: "BW", timezone: "Africa/Gaborone" },
  { label: "Brazil", value: "BRL", code: "BR", timezone: "America/Sao_Paulo" },
  { label: "Brunei", value: "BND", code: "BN", timezone: "Asia/Brunei" },
  { label: "Bulgaria", value: "BGN", code: "BG", timezone: "Europe/Sofia" },
  {
    label: "Burkina Faso",
    value: "XOF",
    code: "BF",
    timezone: "Africa/Ouagadougou",
  },
  { label: "Burundi", value: "BIF", code: "BI", timezone: "Africa/Bujumbura" },
  { label: "Cambodia", value: "KHR", code: "KH", timezone: "Asia/Phnom_Penh" },
  { label: "Cameroon", value: "XAF", code: "CM", timezone: "Africa/Douala" },
  { label: "Canada", value: "CAD", code: "CA", timezone: "America/Toronto" },
  {
    label: "Cape Verde",
    value: "CVE",
    code: "CV",
    timezone: "Atlantic/Cape_Verde",
  },
  {
    label: "Central African Republic",
    value: "XAF",
    code: "CF",
    timezone: "Africa/Bangui",
  },
  { label: "Chad", value: "XAF", code: "TD", timezone: "Africa/Ndjamena" },
  { label: "Chile", value: "CLP", code: "CL", timezone: "America/Santiago" },
  { label: "China", value: "CNY", code: "CN", timezone: "Asia/Shanghai" },
  { label: "Colombia", value: "COP", code: "CO", timezone: "America/Bogota" },
  { label: "Comoros", value: "KMF", code: "KM", timezone: "Indian/Comoro" },
  { label: "Congo", value: "XAF", code: "CG", timezone: "Africa/Brazzaville" },
  {
    label: "Costa Rica",
    value: "CRC",
    code: "CR",
    timezone: "America/Costa_Rica",
  },
  { label: "Croatia", value: "HRK", code: "HR", timezone: "Europe/Zagreb" },
  { label: "Cuba", value: "CUP", code: "CU", timezone: "America/Havana" },
  { label: "Cyprus", value: "EUR", code: "CY", timezone: "Asia/Nicosia" },
  {
    label: "Czech Republic",
    value: "CZK",
    code: "CZ",
    timezone: "Europe/Prague",
  },
  {
    label: "Democratic Republic of the Congo",
    value: "CDF",
    code: "CD",
    timezone: "Africa/Kinshasa",
  },
  { label: "Denmark", value: "DKK", code: "DK", timezone: "Europe/Copenhagen" },
  { label: "Djibouti", value: "DJF", code: "DJ", timezone: "Africa/Djibouti" },
  { label: "Dominica", value: "XCD", code: "DM", timezone: "America/Dominica" },
  {
    label: "Dominican Republic",
    value: "DOP",
    code: "DO",
    timezone: "America/Santo_Domingo",
  },
  { label: "East Timor", value: "USD", code: "TL", timezone: "Asia/Dili" },
  { label: "Ecuador", value: "USD", code: "EC", timezone: "America/Guayaquil" },
  { label: "Egypt", value: "EGP", code: "EG", timezone: "Africa/Cairo" },
  {
    label: "El Salvador",
    value: "USD",
    code: "SV",
    timezone: "America/El_Salvador",
  },
  {
    label: "Equatorial Guinea",
    value: "XAF",
    code: "GQ",
    timezone: "Africa/Malabo",
  },
  { label: "Eritrea", value: "ERN", code: "ER", timezone: "Africa/Asmara" },
  { label: "Estonia", value: "EUR", code: "EE", timezone: "Europe/Tallinn" },
  {
    label: "Ethiopia",
    value: "ETB",
    code: "ET",
    timezone: "Africa/Addis_Ababa",
  },
  { label: "Fiji", value: "FJD", code: "FJ", timezone: "Pacific/Fiji" },
  { label: "Finland", value: "EUR", code: "FI", timezone: "Europe/Helsinki" },
  { label: "France", value: "EUR", code: "FR", timezone: "Europe/Paris" },
  { label: "Gabon", value: "XAF", code: "GA", timezone: "Africa/Libreville" },
  { label: "Gambia", value: "GMD", code: "GM", timezone: "Africa/Banjul" },
  { label: "Georgia", value: "GEL", code: "GE", timezone: "Asia/Tbilisi" },
  { label: "Germany", value: "EUR", code: "DE", timezone: "Europe/Berlin" },
  { label: "Ghana", value: "GHS", code: "GH", timezone: "Africa/Accra" },
  { label: "Greece", value: "EUR", code: "GR", timezone: "Europe/Athens" },
  { label: "Grenada", value: "XCD", code: "GD", timezone: "America/Grenada" },
  {
    label: "Guatemala",
    value: "GTQ",
    code: "GT",
    timezone: "America/Guatemala",
  },
  { label: "Guinea", value: "GNF", code: "GN", timezone: "Africa/Conakry" },
  {
    label: "Guinea-Bissau",
    value: "XOF",
    code: "GW",
    timezone: "Africa/Bissau",
  },
  { label: "Guyana", value: "GYD", code: "GY", timezone: "America/Guyana" },
  {
    label: "Haiti",
    value: "HTG",
    code: "HT",
    timezone: "America/Port-au-Prince",
  },
  {
    label: "Honduras",
    value: "HNL",
    code: "HN",
    timezone: "America/Tegucigalpa",
  },
  { label: "Hungary", value: "HUF", code: "HU", timezone: "Europe/Budapest" },
  {
    label: "Iceland",
    value: "ISK",
    code: "IS",
    timezone: "Atlantic/Reykjavik",
  },
  { label: "India", value: "INR", code: "IN", timezone: "Asia/Kolkata" },
  { label: "Indonesia", value: "IDR", code: "ID", timezone: "Asia/Jakarta" },
  { label: "Iran", value: "IRR", code: "IR", timezone: "Asia/Tehran" },
  { label: "Iraq", value: "IQD", code: "IQ", timezone: "Asia/Baghdad" },
  { label: "Ireland", value: "EUR", code: "IE", timezone: "Europe/Dublin" },
  { label: "Israel", value: "ILS", code: "IL", timezone: "Asia/Jerusalem" },
  { label: "Italy", value: "EUR", code: "IT", timezone: "Europe/Rome" },
  {
    label: "Ivory Coast",
    value: "XOF",
    code: "CI",
    timezone: "Africa/Abidjan",
  },
  { label: "Jamaica", value: "JMD", code: "JM", timezone: "America/Jamaica" },
  { label: "Japan", value: "JPY", code: "JP", timezone: "Asia/Tokyo" },
  { label: "Jordan", value: "JOD", code: "JO", timezone: "Asia/Amman" },
  { label: "Kazakhstan", value: "KZT", code: "KZ", timezone: "Asia/Almaty" },
  { label: "Kenya", value: "KES", code: "KE", timezone: "Africa/Nairobi" },
  { label: "Kiribati", value: "AUD", code: "KI", timezone: "Pacific/Tarawa" },
  { label: "Kuwait", value: "KWD", code: "KW", timezone: "Asia/Kuwait" },
  { label: "Kyrgyzstan", value: "KGS", code: "KG", timezone: "Asia/Bishkek" },
  { label: "Laos", value: "LAK", code: "LA", timezone: "Asia/Vientiane" },
  { label: "Latvia", value: "EUR", code: "LV", timezone: "Europe/Riga" },
  { label: "Lebanon", value: "LBP", code: "LB", timezone: "Asia/Beirut" },
  { label: "Lesotho", value: "LSL", code: "LS", timezone: "Africa/Maseru" },
  { label: "Liberia", value: "LRD", code: "LR", timezone: "Africa/Monrovia" },
  { label: "Libya", value: "LYD", code: "LY", timezone: "Africa/Tripoli" },
  {
    label: "Liechtenstein",
    value: "CHF",
    code: "LI",
    timezone: "Europe/Vaduz",
  },
  { label: "Lithuania", value: "EUR", code: "LT", timezone: "Europe/Vilnius" },
  {
    label: "Luxembourg",
    value: "EUR",
    code: "LU",
    timezone: "Europe/Luxembourg",
  },
  {
    label: "Madagascar",
    value: "MGA",
    code: "MG",
    timezone: "Indian/Antananarivo",
  },
  { label: "Malawi", value: "MWK", code: "MW", timezone: "Africa/Blantyre" },
  {
    label: "Malaysia",
    value: "MYR",
    code: "MY",
    timezone: "Asia/Kuala_Lumpur",
  },
  { label: "Maldives", value: "MVR", code: "MV", timezone: "Indian/Maldives" },
  { label: "Mali", value: "XOF", code: "ML", timezone: "Africa/Bamako" },
  { label: "Malta", value: "EUR", code: "MT", timezone: "Europe/Malta" },
  {
    label: "Marshall Islands",
    value: "USD",
    code: "MH",
    timezone: "Pacific/Majuro",
  },
  {
    label: "Mauritania",
    value: "MRU",
    code: "MR",
    timezone: "Africa/Nouakchott",
  },
  {
    label: "Mauritius",
    value: "MUR",
    code: "MU",
    timezone: "Indian/Mauritius",
  },
  {
    label: "Mexico",
    value: "MXN",
    code: "MX",
    timezone: "America/Mexico_City",
  },
  {
    label: "Micronesia",
    value: "USD",
    code: "FM",
    timezone: "Pacific/Pohnpei",
  },
  { label: "Moldova", value: "MDL", code: "MD", timezone: "Europe/Chisinau" },
  { label: "Monaco", value: "EUR", code: "MC", timezone: "Europe/Monaco" },
  { label: "Mongolia", value: "MNT", code: "MN", timezone: "Asia/Ulaanbaatar" },
  {
    label: "Montenegro",
    value: "EUR",
    code: "ME",
    timezone: "Europe/Podgorica",
  },
  { label: "Morocco", value: "MAD", code: "MA", timezone: "Africa/Casablanca" },
  { label: "Mozambique", value: "MZN", code: "MZ", timezone: "Africa/Maputo" },
  { label: "Myanmar", value: "MMK", code: "MM", timezone: "Asia/Yangon" },
  { label: "Namibia", value: "NAD", code: "NA", timezone: "Africa/Windhoek" },
  { label: "Nauru", value: "AUD", code: "NR", timezone: "Pacific/Nauru" },
  { label: "Nepal", value: "NPR", code: "NP", timezone: "Asia/Kathmandu" },
  {
    label: "Netherlands",
    value: "EUR",
    code: "NL",
    timezone: "Europe/Amsterdam",
  },
  {
    label: "New Zealand",
    value: "NZD",
    code: "NZ",
    timezone: "Pacific/Auckland",
  },
  { label: "Nicaragua", value: "NIO", code: "NI", timezone: "America/Managua" },
  { label: "Niger", value: "XOF", code: "NE", timezone: "Africa/Niamey" },
  { label: "Nigeria", value: "NGN", code: "NG", timezone: "Africa/Lagos" },
  {
    label: "North Korea",
    value: "KPW",
    code: "KP",
    timezone: "Asia/Pyongyang",
  },
  {
    label: "North Macedonia",
    value: "MKD",
    code: "MK",
    timezone: "Europe/Skopje",
  },
  { label: "Norway", value: "NOK", code: "NO", timezone: "Europe/Oslo" },
  { label: "Oman", value: "OMR", code: "OM", timezone: "Asia/Muscat" },
  { label: "Pakistan", value: "PKR", code: "PK", timezone: "Asia/Karachi" },
  { label: "Palau", value: "USD", code: "PW", timezone: "Pacific/Palau" },
  { label: "Palestine", value: "ILS", code: "PS", timezone: "Asia/Gaza" },
  { label: "Panama", value: "PAB", code: "PA", timezone: "America/Panama" },
  {
    label: "Papua New Guinea",
    value: "PGK",
    code: "PG",
    timezone: "Pacific/Port_Moresby",
  },
  { label: "Paraguay", value: "PYG", code: "PY", timezone: "America/Asuncion" },
  { label: "Peru", value: "PEN", code: "PE", timezone: "America/Lima" },
  { label: "Philippines", value: "PHP", code: "PH", timezone: "Asia/Manila" },
  { label: "Poland", value: "PLN", code: "PL", timezone: "Europe/Warsaw" },
  { label: "Portugal", value: "EUR", code: "PT", timezone: "Europe/Lisbon" },
  { label: "Qatar", value: "QAR", code: "QA", timezone: "Asia/Qatar" },
  { label: "Romania", value: "RON", code: "RO", timezone: "Europe/Bucharest" },
  { label: "Russia", value: "RUB", code: "RU", timezone: "Europe/Moscow" },
  { label: "Rwanda", value: "RWF", code: "RW", timezone: "Africa/Kigali" },
  {
    label: "Saint Kitts and Nevis",
    value: "XCD",
    code: "KN",
    timezone: "America/St_Kitts",
  },
  {
    label: "Saint Lucia",
    value: "XCD",
    code: "LC",
    timezone: "America/St_Lucia",
  },
  {
    label: "Saint Vincent and the Grenadines",
    value: "XCD",
    code: "VC",
    timezone: "America/St_Vincent",
  },
  { label: "Samoa", value: "WST", code: "WS", timezone: "Pacific/Apia" },
  {
    label: "San Marino",
    value: "EUR",
    code: "SM",
    timezone: "Europe/San_Marino",
  },
  {
    label: "Sao Tome and Principe",
    value: "STN",
    code: "ST",
    timezone: "Africa/Sao_Tome",
  },
  { label: "Saudi Arabia", value: "SAR", code: "SA", timezone: "Asia/Riyadh" },
  { label: "Senegal", value: "XOF", code: "SN", timezone: "Africa/Dakar" },
  { label: "Serbia", value: "RSD", code: "RS", timezone: "Europe/Belgrade" },
  { label: "Seychelles", value: "SCR", code: "SC", timezone: "Indian/Mahe" },
  {
    label: "Sierra Leone",
    value: "SLL",
    code: "SL",
    timezone: "Africa/Freetown",
  },
  { label: "Singapore", value: "SGD", code: "SG", timezone: "Asia/Singapore" },
  {
    label: "Slovakia",
    value: "EUR",
    code: "SK",
    timezone: "Europe/Bratislava",
  },
  { label: "Slovenia", value: "EUR", code: "SI", timezone: "Europe/Ljubljana" },
  {
    label: "Solomon Islands",
    value: "SBD",
    code: "SB",
    timezone: "Pacific/Guadalcanal",
  },
  { label: "Somalia", value: "SOS", code: "SO", timezone: "Africa/Mogadishu" },
  {
    label: "South Africa",
    value: "ZAR",
    code: "ZA",
    timezone: "Africa/Johannesburg",
  },
  { label: "South Korea", value: "KRW", code: "KR", timezone: "Asia/Seoul" },
  { label: "South Sudan", value: "SSP", code: "SS", timezone: "Africa/Juba" },
  { label: "Spain", value: "EUR", code: "ES", timezone: "Europe/Madrid" },
  { label: "Sri Lanka", value: "LKR", code: "LK", timezone: "Asia/Colombo" },
  { label: "Sudan", value: "SDG", code: "SD", timezone: "Africa/Khartoum" },
  {
    label: "Suriname",
    value: "SRD",
    code: "SR",
    timezone: "America/Paramaribo",
  },
  { label: "Sweden", value: "SEK", code: "SE", timezone: "Europe/Stockholm" },
  { label: "Switzerland", value: "CHF", code: "CH", timezone: "Europe/Zurich" },
  { label: "Syria", value: "SYP", code: "SY", timezone: "Asia/Damascus" },
  { label: "Taiwan", value: "TWD", code: "TW", timezone: "Asia/Taipei" },
  { label: "Tajikistan", value: "TJS", code: "TJ", timezone: "Asia/Dushanbe" },
  {
    label: "Tanzania",
    value: "TZS",
    code: "TZ",
    timezone: "Africa/Dar_es_Salaam",
  },
  { label: "Thailand", value: "THB", code: "TH", timezone: "Asia/Bangkok" },
  { label: "Togo", value: "XOF", code: "TG", timezone: "Africa/Lome" },
  { label: "Tonga", value: "TOP", code: "TO", timezone: "Pacific/Tongatapu" },
  {
    label: "Trinidad and Tobago",
    value: "TTD",
    code: "TT",
    timezone: "America/Port_of_Spain",
  },
  { label: "Tunisia", value: "TND", code: "TN", timezone: "Africa/Tunis" },
  { label: "Turkey", value: "TRY", code: "TR", timezone: "Europe/Istanbul" },
  {
    label: "Turkmenistan",
    value: "TMT",
    code: "TM",
    timezone: "Asia/Ashgabat",
  },
  { label: "Tuvalu", value: "AUD", code: "TV", timezone: "Pacific/Funafuti" },
  { label: "Uganda", value: "UGX", code: "UG", timezone: "Africa/Kampala" },
  { label: "Ukraine", value: "UAH", code: "UA", timezone: "Europe/Kiev" },
  {
    label: "United Arab Emirates",
    value: "AED",
    code: "AE",
    timezone: "Asia/Dubai",
  },
  {
    label: "United Kingdom",
    value: "GBP",
    code: "GB",
    timezone: "Europe/London",
  },
  {
    label: "United States",
    value: "USD",
    code: "US",
    timezone: "America/New_York",
  },
  {
    label: "Uruguay",
    value: "UYU",
    code: "UY",
    timezone: "America/Montevideo",
  },
  { label: "Uzbekistan", value: "UZS", code: "UZ", timezone: "Asia/Tashkent" },
  { label: "Vanuatu", value: "VUV", code: "VU", timezone: "Pacific/Efate" },
  {
    label: "Vatican City",
    value: "EUR",
    code: "VA",
    timezone: "Europe/Vatican",
  },
  { label: "Venezuela", value: "VES", code: "VE", timezone: "America/Caracas" },
  { label: "Vietnam", value: "VND", code: "VN", timezone: "Asia/Ho_Chi_Minh" },
  { label: "Yemen", value: "YER", code: "YE", timezone: "Asia/Aden" },
  { label: "Zambia", value: "ZMW", code: "ZM", timezone: "Africa/Lusaka" },
  { label: "Zimbabwe", value: "ZWL", code: "ZW", timezone: "Africa/Harare" },
];

export default countries;
